### ISSUE TITLE
Remove the fee option?

### ISSUE THREAD

**Issue by sigmike** [peercoin/peercoin#148]
There are options in the client to change the transaction fee (in the GUI and with the `settxfee` RPC). These options should probably be removed in Peercoin since the transaction fee is fixed by the protocol.

**Comment by saeveritt** [comment]
The minimum transaction fee is fixed by protocol though is it possible there could come a time where blocks become full and competitive fees are warranted? Would it not be in the minters and miners best interest to choose to include the transactions with the highest PPC/kb rate in order to reduce total supply?

**Comment by sigmike** [comment]
Indeed there's a potential use so it's probably not worth removing. And the client already prioritizes by fee when the block reaches a certain size.
