### ISSUE TITLE
Transaction timestamps incorrectly displayed in Qt UI

### ISSUE THREAD

**Issue by hrobeers** [peercoin/peercoin#156]
After a fresh blockchain download I imported my private keys (using importprivkey).
To my surprise, many old transactions where displayed as if they happened yesterday while some even have over 50000 confirmations.

I checked on the chain, all seems to be fine, so looks like a display issue.

Will investigate, but any pointers are welcome.

![txtime_bug](https://user-images.githubusercontent.com/2812522/28961021-1423c9c8-7901-11e7-9e79-26df9d80aa3a.png)

**Comment by sigmike** [comment]
I think it has always been like that because that's how bitcoin does it. The transaction time is the time when it was first seen by the wallet. In the RPC `listtransactions` both times are returned (`time` and `timereceived`).

Since in Peercoin transactions have their own time we should probably use that here instead. But not if we're going to remove it.

**Comment by hrobeers** [comment]
We won't remove it in v0.6 yet.
If it always has been like that, it probably isn't that big of an issue.
I'll take a quick look if it's a simple fix, otherwise I'm ok to ignore this for now.

**Comment by hrobeers** [comment]
Fixed by https://github.com/peercoin/peercoin/pull/160
