### ISSUE TITLE
Not able to sync after a while running the client

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#188]
![selection_012](https://user-images.githubusercontent.com/6118832/31427953-5d06427c-ae69-11e7-8ac2-eeb618596e8a.png)

I guess that is due to the fork?

**Comment by sandakersmann** [comment]
I'm at block 300248 now and no out of sync message. I guess the two forks are neck-and-neck racing to be the longest.

**Comment by sandakersmann** [comment]
This client is built from the develop branch by the way.

**Comment by hrobeers** [comment]
Yes this caused by the fork.
There are no sync checkpoints broadcasted on testnet, so the `develop` (non-fork) client accepts the orphans created by v0.5 clients.

Your client should always eventually switch to the v0.6 branch. If you stay stuck for more than a few hours, feel free to reopen this issue.

**Comment by Quix0r** [comment]
I'm having the same issue with latest `master` branch: de95f5100b1f2c20d38169a37087c35cca5897d9

**Comment by backpacker69** [comment]
> I'm having the same issue with latest `master` branch: [de95f51](https://github.com/peercoin/peercoin/commit/de95f5100b1f2c20d38169a37087c35cca5897d9)

you'll have to resync from scratch, as you are too far past fork date for fork resolution to happen automatically.

**Comment by Quix0r** [comment]
That did work, @backpacker69 thank you. :-) So clearing `~/.ppcoin/<blocks|chainstate|database>/` did the trick here.
