### ISSUE TITLE
Minting Tab Colors

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin#224]
The minting tab is now confusing because the colors were switched. It is currently setup like this...

Immature - Blue
Mature - Green
Maximum Probability - Red

Red is usually is associated with something negative, so using it to signal maximum probability is not very intuitive. Red should only mean immature. Green should mean maximum probability. Blue is not part of Peercoin's color scheme. I think it makes more sense to use a lighter green color instead of blue. So it should look like this instead...

Immature - Red
Mature - Lighter Green
Maximum Probability - Peercoin Green #3cb054

**Comment by ticalc-travis** [comment]
Although colors are handy for those who can see and distinguish them easily, they have potential usability/accessibility pitfalls. At first, I found even Peerunity's light green vs. dark green rather confusing until I actually had entries from both shades of green in the list at the same time. The shades were similar enough that I had difficulty telling which was which when only one of the two was present in the list.

But an even bigger problem is that it's currently impossible to tell the transactions that are currently highlighted from those that are green (mature), because both use the same color. That is confusing and misleading, especially when multiple transactions are highlighted.

I think that a better solution might be to use a column with icons or text labels to indicate status (in addition to, or in place of colors). Don't forget that there is a significant number of color-blind users out there as well (and even those with no vision at all). In UI design, using colors as a sole means of conveying information is not generally considered a good idea.
