### ISSUE TITLE
illusive coins in wallet (balance was wrong)

### ISSUE THREAD

**Issue by PSLLSP** [peercoin/peercoin#529]
peercoin-0.8.5

I installed peercoin (linux-64) to a new PC. I imported private key with "importprivkey". Once sync was finished, I was surprised to find that I have more coins than I expected (QT client). I verified with "getbalance", it reported the same value. I expected to have about 55 coins but 77 coins were reported. I listed transactions (listtransactions) but there was no evidence for extra coins. I rescaned blockchain (rescanblockchain) and balance was fixed, to 55 coins. Difference was 17.400945 PPC, these 17 coins were reported but were not in the wallet.. I don't remember I ever spent a single PPC coin from this wallet. Do you have an idea, what was source of these illusive coins?

**Comment by backpacker69** [comment]
please do the following if you don't mind, since you have privkey and haven't spent any coins:

backup ~/.peercoin/debug.log

1. stop peercoin wallet
2. mv ~/.peercoin/debug.log  ~/.peercoin/debug.log.backup
3. set debug=1 in your peercoin.conf
4. mv ~/.peercoin/wallets/wallet.dat ~/.peercoin/wallets/wallet.dat.wtf
5. start wallet
6. importprivkey again
7. verify balance
if it's correct (55 coins) we are SOL. please send me your  ~/.peercoin/debug.log.backup
if not, great, continue:
8. stop wallet
9. mv ~/.peercoin/debug.log  ~/.peercoin/debug.log.beforerescan
10. start wallet with rescanblockchain
wait for it to finish, verify balance is correct (55) and send me full debug.log, debug.log.backup and debug.log.beforerescan
 
zip them and send to backpacker69@protonmail.com so i might be able to see something.

**Comment by PSLLSP** [comment]
I did it but there was third option. In step 7, getbalance reported 77 coins. I stopped wallet and moved debug.log to debug.log.beforescan. I started wallet again (step 10) and checked balance. It was 55! No rescan command was executed. I am going to send debug file to the email.

**Comment by PSLLSP** [comment]
I read log file, I see 3 messages that some coins were spent, about 17.004 PPC together...
"WalletUpdateSpent found spent coin" This is wrong information. And when these 17 coins were spent, why are these added to the balance? I assume these should be subtracted. Anyway, nothing was spent, I cannot see such transaction in transaction history...

**Comment by backpacker69** [comment]
very strange, can you please test the same thing with 0.9.0 version and send me the log again?

**Comment by PSLLSP** [comment]
Yes, I confirm that wallet 0.9.0 has the same behavior. I can replicate this problem when private key is imported....

**Comment by backpacker69** [comment]
thank you for your bug report, found the problem and fixed it in release-0.9, should be available when 0.9.1 comes out after the fork.
