### ISSUE TITLE
IRC server (irc.lfnet.org) is dead

### ISSUE THREAD

**Issue by Thireus** [peercoin/peercoin#85]
We should use our own IRC server. 

irc.lfnet.org seems dead, people are having trouble connecting to Peercoin's network: https://github.com/ppcoin/ppcoin/blob/master/src/irc.cpp#L223-L225

Also it would be a good idea to have our channels named "#peercoinXX"instead of "#bitcoinXX": https://github.com/ppcoin/ppcoin/blob/master/src/irc.cpp#L295-L303

**Comment by MatthewLM** [comment]
I personally suggest ditching IRC much like Bitcoin has, and using a more reliable DNS system, where the domains are owned by several trust-worthy entities, and use a DNS server that tracks reliable peers on the network in realtime. Perhaps I could set-up my own DNS server using sipa's code adapted for Peercoin here: https://github.com/sipa/bitcoin-seeder which I could setup under my peercoinexplorer.info domain.

I would happily volunteer for that.

**Comment by thokon00** [comment]
Being a fan of PPC I would also be willing to help. I could port the bitcoin-seeder Matthew mentioned to PPC. I already did that for our network, see here: https://github.com/FairCoinTeam/faircoin-seeder. I'm running two FairCoin seeds without any problems since months so far. Also if desired I would be willing to run a dynamic seed node if you want for free. Please get in touch, my PGP key is 0x21792BF5.

**Comment by thokon00** [comment]
Here you go, I created a port for Peercoin: https://github.com/thokon00/ppcoin-seeder

**Comment by Thireus** [comment]
Thank you for this @thokon00!
